url: /n-week-project
theme: null
permalink: /:collection/:name
collections_dir: chapters

collections:
  c:
    name: Chemistry
    output: true
  m:
    name: Mathematics
    output: true
  p:
    name: Physics
    output: true